image: maven:3.9.9-eclipse-temurin-17  # Образ с Maven и eclipse temurin JDK 17

# Определяем стадии пайплайна
stages:
  - build
  - test

# Шаг для сборки проекта
build:
  stage: build
  script:
    - echo "Building project..."
    - mvn clean install  # Сборка и установка зависимостей
  only:
    - master  # Выполняется только для ветки master

# Шаг для запуска тестов
test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn clean test  # Запуск тестов с Maven
  only:
    - master  # Выполняется только для ветки master
