image: maven:3.9.9-eclipse-temurin-21  # Eclipse temurin image with java v21

# Pipeline stages
stages:
  - build
  - test

# Building stage
build:
  stage: build
  script:
    - echo "Building project..."
    - mvn clean install  # Maven start building command
  only:
    - master  # Only 'master' branch changes

# Testing stage
test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn clean test  # Maven test start command
  only:
    - master  # Only 'master' branch changes