# Dockerfile.core-api-service
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /build

COPY /pom.xml /pom.xml
COPY /core-api-service/src /core-api-service/src
COPY /core-api-service/pom.xml /core-api-service/pom.xml

RUN mvn -f /core-api-service/pom.xml clean package -DskipTests

FROM eclipse-temurin:21.0.4_7-jre-jammy

WORKDIR /app

COPY --from=build core-api-service/target/core-api-service.jar ./core-api-service.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "./core-api-service.jar"]