spring:
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME:admin_user_username}
      password: ${SPRING_SECURITY_PASSWORD:admin_user_password}
      roles:
        - MANAGER
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres_db:5432/business_manager}
    username: ${SPRING_DATASOURCE_USERNAME:database_user}
    password: ${SPRING_DATASOURCE_PASSWORD:database_user_password}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: false
    schemas: core_api_service
  jpa:
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_DATASOURCE_URL:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  api-docs:
    enabled: true
    path: /manager-api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /manager-api/swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}
  info:
    env:
      enabled: true

info:
  app:
    name: Business manager - Core API
    description: Backend service implemented in Java to handle business logic and data.
    version: 1.1.0

server:
  port: 8081