spring:
  security:
    user:
      name: admin_user_username
      password: admin_user_password
      roles:
        - MANAGER
  datasource:
    url: jdbc:postgresql://postgres_db:5432/business_manager
    username: database_user
    password: database_user_password
  flyway:
    schemas:
      - public
      - manager
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info