spring:
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
      roles:
        - MANAGER
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    schemas:
      - public
      - manager
  jpa:
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_DATASOURCE_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  api-docs:
    enabled: true
    path: /manager-api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /manager-api/swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
  info:
    env:
      enabled: true

info:
  app:
    name: Business manager - Core API
    description: Backend service implemented in Java to handle business logic and data.
    version: 1.1.0

server:
  port: 8081