spring:
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}
      roles:
        - MANAGER
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    schemas:
      - public
      - manager
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info