apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-api-service
  template:
    metadata:
      labels:
        app: core-api-service
    spec:
      containers:
        - name: core-api-service
          image: business-manager-core-api-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: core-api-service-config