apiVersion: v1
kind: Service
metadata:
  name: core-api-service
spec:
  type: NodePort
  selector:
    app: core-api-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
