# Dockerfile.manager-ui-app
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /build

COPY /pom.xml /pom.xml
COPY /manager-ui-app/src /manager-ui-app/src
COPY /manager-ui-app/pom.xml /manager-ui-app/pom.xml

RUN mvn -f /manager-ui-app/pom.xml clean package -DskipTests

FROM eclipse-temurin:21.0.4_7-jre-jammy

WORKDIR /app

COPY --from=build manager-ui-app/target/manager-ui-app.jar ./manager-ui-app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "./manager-ui-app.jar"]
