apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: "3.7.0"
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    storage:
      type: persistent-claim
      size: 5Gi
      class: standard
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      class: standard
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 5