apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-ui-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-ui-app
  template:
    metadata:
      labels:
        app: manager-ui-app
    spec:
      containers:
        - name: manager-ui-app
          image: business-manager-manager-ui-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: manager-ui-app-config