apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deploy
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deploy
  template:
    metadata:
      labels:
        app: postgres-deploy
    spec:
      containers:
        - name: postgres-deploy
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "business_manager"
            - name: POSTGRES_USER
              value: "database_user"
            - name: POSTGRES_PASSWORD
              value: "database_user_password"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
