apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deploy
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deploy
  template:
    metadata:
      labels:
        app: postgres-deploy
    spec:
      containers:
        - name: postgres-deploy
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
