spring:
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}

business-manager:
  services:
    manager-api:
      uri: ${CORE_API_SERVICE_URI}
      username: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}

      clients:
        uri: /manager-api/clients
      proposals:
        uri: /manager-api/proposals
      appointments:
        uri: /manager-api/appointments

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
  info:
    env:
      enabled: true

info:
  app:
    name: Business manager MANAGER UI
    description: Web application for managing users and data.
    version: 1.1.0

server:
  port: 8080