spring:
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME:admin_user_username}
      password: ${SPRING_SECURITY_PASSWORD:admin_user_password}

business-manager:
  services:
    manager-api:
      uri: ${CORE_API_SERVICE_URI:http://core-api-service:8081}
      username: ${SPRING_SECURITY_USERNAME:admin_user_username}
      password: ${SPRING_SECURITY_PASSWORD:admin_user_password}

      clients:
        uri: /manager-api/clients
      proposals:
        uri: /manager-api/proposals
      appointments:
        uri: /manager-api/appointments

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
  info:
    env:
      enabled: true

info:
  app:
    name: Business manager - Manager UI
    description: Web application for managing users and data.
    version: 1.1.0

server:
  port: 8080