spring:
  security:
    user:
      name: admin_user_username
      password: admin_user_password

business-manager:
  services:
    manager-api:
      uri: http://localhost:8081
      username: admin_user_username
      password: admin_user_password

      clients:
        uri: /manager-api/clients
      proposals:
        uri: /manager-api/proposals
      appointments:
        uri: /manager-api/appointments