apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  # Datasource settings
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/business_manager"
  SPRING_DATASOURCE_USERNAME: "database_user"
  SPRING_DATASOURCE_PASSWORD: "database_user_password"
  # Kafka settings
  KAFKA_DATASOURCE_URL: "kafka:9092"
  KAFKA_GROUP_ID: "notification-group"
  # Email producer settings
  EMAIL_PASSWORD: "type_your_email_password_here"
  EMAIL_USERNAME: "type_your_email_username_here"
  # Telegram producer settings
  TELEGRAM_BOT_TOKEN: "type_your_telegram_bot_token_here"
  # Actuator settings
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health, info"